# Skinny Bones Gemfile
source "https://rubygems.org"

gem "jekyll"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "webrick"
gem "github-pages", "~> VERSION", group: :jekyll_plugins


gem 'jekyll-compose', group: [:jekyll_plugins]